apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys:
          - server
        generators:
          - clusters:
              values:
                chartName: guestbook
              selector:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - "euw1"
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - "production"
  template:
    metadata:
      name: "{{.nameNormalized}}-guestbook"
      labels:
        chartName: "{{.values.chartName}}"
        appsetFileName: "guestbook-appset"
        environment: "{{.metadata.labels.environment}}"
        type: "workload"
    spec:
      project: default
      source:
        repoURL: "https://github.com/kaminek/gitops"
        targetRevision: HEAD
        path: "charts/{{.values.chartName}}"
        helm:
          releaseName: "{{ .values.chartName }}"
          ignoreMissingValueFiles: true
          valueFiles:
            - gitops/environments/{{.metadata.labels.environment}}/apps/{{.values.chartName}}/values.yaml
            - gitops/clusters/{{.name}}/apps/{{.values.chartName}}/values.yaml
          valuesObject:
            replicaCount: 1
            tolerations:
              - key: "eks-addons"
                operator: "Exists"
                effect: "NoSchedule"
            nodeSelector:
              karpenter.sh/nodepool: eks-addons
              kubernetes.io/arch: amd64
      destination:
        namespace: "{{.values.chartName}}"
        name: "{{.name}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
